apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wi2ol9f0g-java-quarkus
  janus-idp.io/tekton: wi2ol9f0g-java-quarkus
  backstage.io/kubernetes-id: wi2ol9f0g-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: wi2ol9f0g-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
