apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: wi2ol9f0g-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/wi2ol9f0g-java-quarkus-gitops